version: '3.8'
services:
  web:
    image: httpd:latest
    container_name: cevdetabbas.com
    ports:
      - "1880:80"
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs/
      - ./id_ed25519:/root/.ssh/id_ed25519:ro
      - ./id_ed25519.pub:/root/.ssh/id_ed25519.pub:ro
      - ./known_hosts:/root/.ssh/known_hosts:ro
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y git openssh-client &&
        chmod 600 /root/.ssh/id_ed25519 &&
        while true; do
          git -C /usr/local/apache2 pull origin main;
          sleep 60;
        done
      "
    restart: always
