---
services:
  web:
    image: httpd:latest
    container_name: cevdetabbas.com
    ports:
      - "1880:80"
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs/
      - ./id_ed25519:/root/.ssh/id_ed25519
      - ./id_ed25519.pub:/root/.ssh/id_ed25519.pub
      - ./nmapinstall.sh:/root/nmapinstall.sh
    command: >
      bash -c "
        apt-get update &&
        apt install -y nmap git &&
        httpd-foreground
      "
    restart: always
