---
services:
  web:
    image: httpd:latest  # Official Apache HTTP Server image
    container_name: cevdetabbas.cevdetabbas.com
    ports:
      - "1880:80"  # Map port 80 in the container to port 8080 on the host
    volumes:
      - ./htdocks:/usr/local/apache2/htdocs/  # Mount a local directory for website files
    restart: always  # Ensure the container restarts if it stops

